[terminal]
shell = "/opt/homebrew/bin/fish"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
decorations = "Full"

[window.padding]
x = 8
y = 0

[font]
size = 16.0

[font.normal]
family = "DankMono Nerd Font"
style = "Regular"

[cursor]
style = "Block"


[colors.selection]
text = "#0e1128"
background = "#f4e4c9"

[colors.primary]
background = "#0e1128"
foreground = "#f4e4c9"

[colors.cursor]
text = "#0e1128"
cursor = "#f4a5c3"

[colors.normal]
black = "#1a1a1a"
red = "#f78a62"
green = "#44c0c3"
yellow = "#f4a5c3"
blue = "#a382ff"
magenta = "#f4a5c3"
cyan = "#44c0c3"
white = "#f4e4c9"

[colors.bright]
black = "#3d3d3d"
red = "#ff9a7a"
green = "#6bcdcf"
yellow = "#f6d3e0"
blue = "#bba9ff"
magenta = "#f6c4d6"
cyan = "#90dadb"
white = "#ffffff"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"
