shell = "/opt/homebrew/bin/fish"

[font]
size = 15

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[window]
opacity = 0.65
blur = true
dimensions = { columns = 140, lines = 40 }
startup_mode = "Windowed"                  # Other options Windowed, Maximized, Fullscreen and SimpleFullscreen
decorations = "Buttonless"

# Kanagawa Dragon Alacritty Colors
[colors]
selection = { text = '#C8C093', background = '#2D4F67' }
indexed_colors = [
  { index = 16, color = '#b6927b' },
  { index = 17, color = '#b98d7b' },
]

[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#C8C093'

[colors.bright]
black = '#a6a69c'
red = '#E46876'
green = '#87a987'
yellow = '#E6C384'
blue = '#7FB4CA'
magenta = '#938AA9'
cyan = '#7AA89F'
white = '#c5c9c5'
