set -g mode-style "fg=#fdf6e3,bg=#b58900,bold"
set -g message-style "fg=#073642,bg=#e9e1c8"
set -g message-command-style "fg=#073642,bg=#e9e1c8"
set -g pane-border-style "fg=#c4bda8"
set -g pane-active-border-style "fg=#268bd2"
set -g clock-mode-colour "#268bd2"
set -g display-panes-colour "#c4bda8"
set -g display-panes-active-colour "#268bd2"
set -g status-style "fg=#073642,bg=#eee8d5"
set -g status-left-length 24
set -g status-right-length 80
set -g status-left "#[fg=#fdf6e3,bg=#268bd2,bold] #S #[fg=#268bd2,bg=#eee8d5,nobold]"
set -g status-right "#[fg=#93a1a1,bg=#eee8d5]#{?client_prefix,#[fg=#dc322f]PREFIX #[fg=#93a1a1],} %Y-%m-%d %H:%M "
set -g window-status-separator ""
set -g window-status-format "#[fg=#93a1a1,bg=#eee8d5] #I #W "
set -g window-status-current-format "#[fg=#fdf6e3,bg=#268bd2,bold] #I #W "
set -g window-status-activity-style "fg=#b58900,bg=#eee8d5"
set -g window-status-bell-style "fg=#dc322f,bg=#eee8d5,bold"
set -g window-status-last-style "fg=#586e75,bg=#eee8d5"
